// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPM0P5Ih5ulVpoTBYmUiD2MdbXtYghfXA',
    appId: '1:650375015497:web:f3ae359dd0ec8233cca398',
    messagingSenderId: '650375015497',
    projectId: 'health-insurance-blockchain',
    authDomain: 'health-insurance-blockchain.firebaseapp.com',
    storageBucket: 'health-insurance-blockchain.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBky7SNA65ovEo2xfl8tkbs7stYKPe7dfc',
    appId: '1:650375015497:android:0b57cab54c1e29cacca398',
    messagingSenderId: '650375015497',
    projectId: 'health-insurance-blockchain',
    storageBucket: 'health-insurance-blockchain.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPgPHc2dc2x5ZG4u4mNuWxs3d5HMkJRRk',
    appId: '1:650375015497:ios:21f18803fdee2657cca398',
    messagingSenderId: '650375015497',
    projectId: 'health-insurance-blockchain',
    storageBucket: 'health-insurance-blockchain.appspot.com',
    iosClientId: '650375015497-2ie9govvftojrqvfos1eh4ctb906si9v.apps.googleusercontent.com',
    iosBundleId: 'com.example.btpProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPgPHc2dc2x5ZG4u4mNuWxs3d5HMkJRRk',
    appId: '1:650375015497:ios:21f18803fdee2657cca398',
    messagingSenderId: '650375015497',
    projectId: 'health-insurance-blockchain',
    storageBucket: 'health-insurance-blockchain.appspot.com',
    iosClientId: '650375015497-2ie9govvftojrqvfos1eh4ctb906si9v.apps.googleusercontent.com',
    iosBundleId: 'com.example.btpProject',
  );
}
